#!/usr/bin/env bash
# Materialize the reference-repo knowledge base from references/manifest.json.
#
# This is the verification + fetch step that could NOT run in the session that
# authored the manifest (org egress policy blocks GitHub there). Run it in an
# environment that can reach github.com. It shallow-clones each reference repo,
# records the resolved commit SHA for pinning, and flags any that don't exist.
#
# Usage:  scripts/fetch_references.sh
# Output: references/_cache/<owner>__<repo>/   (gitignored working copies)
#         references/pinned.txt                (owner/repo @ sha — commit this)
#
# Nothing here signs transactions or runs any reference repo's code. It only
# clones for reading. Audit before importing anything (see references/README.md).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/references/manifest.json"
CACHE="$ROOT/references/_cache"
PINNED="$ROOT/references/pinned.txt"

command -v git >/dev/null || { echo "git is required"; exit 1; }
command -v python3 >/dev/null || { echo "python3 is required to parse the manifest"; exit 1; }
[ -f "$MANIFEST" ] || { echo "manifest not found: $MANIFEST"; exit 1; }

mkdir -p "$CACHE"
: > "$PINNED"
echo "# owner/repo @ resolved-sha  (generated by scripts/fetch_references.sh)" >> "$PINNED"

# Emit "owner repo audit_flag" lines for every reference, including the Kalshi bucket.
mapfile -t ENTRIES < <(python3 - "$MANIFEST" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))
rows = list(m.get("references", []))
rows += m.get("execution_only_kalshi", {}).get("references", [])
for r in rows:
    print(f"{r['owner']} {r['repo']} {int(bool(r.get('security_audit_required', False)))}")
PY
)

ok=0; missing=0
for line in "${ENTRIES[@]}"; do
  read -r owner repo audit <<< "$line"
  dest="$CACHE/${owner}__${repo}"
  url="https://github.com/${owner}/${repo}.git"

  if [ -d "$dest/.git" ]; then
    echo "↻ updating ${owner}/${repo}"
    git -C "$dest" fetch --depth 1 origin >/dev/null 2>&1 || true
  else
    echo "↓ cloning  ${owner}/${repo}"
    if ! git clone --depth 1 --quiet "$url" "$dest" 2>/dev/null; then
      echo "  ✗ NOT FOUND / unreachable: ${owner}/${repo}"
      echo "${owner}/${repo} @ NOT_FOUND" >> "$PINNED"
      missing=$((missing+1))
      continue
    fi
  fi

  sha="$(git -C "$dest" rev-parse HEAD)"
  flag=""; [ "$audit" = "1" ] && flag="  [SECURITY-AUDIT-REQUIRED before importing]"
  echo "${owner}/${repo} @ ${sha}${flag}" >> "$PINNED"
  ok=$((ok+1))
done

echo
echo "Done: ${ok} fetched, ${missing} missing. Pins written to references/pinned.txt"
echo "Working copies are in references/_cache/ (gitignored). Audit before importing."
